### ISSUE TITLE
bug: pat connects if QSY fails

### ISSUE THREAD

**Issue by DC7IA** [la5nta/pat#219] opened 2020-09-24 22:24 UTC
Pat proceeds to connect even if QSY failed. This leads to pat transmitting on the wrong frequency.

```
2020/09/25 00:21:50 QSY failed: Unable to get rig frequency: dial tcp [::1]:4532: connect: connection refused
2020/09/25 00:21:56 Connecting to OE9XRK (pactor)...
```
Not good if I was listening to shortwave radio and then pat suddenly starts to transmit out of band. :D

**Comment by martinhpedersen** [comment] 2020-09-24 23:14
Thanks for reaching out Joshua.

This is actually a feature, not a bug. Pat will refuse to connect if the QSY request is sent *with* the connect command, but this is not what happened in your case judging from your log:

1. You manually entered a frequency or selected a node from the RMS list in the Web GUI
2. You got a red boarder around the frequency field and an error message in the log indicating that Pat was unable to QSY.
3. 6 seconds later, you hit the Connect button anyway.

Does this sound about right?

In these cases where Pat is told to QSY the rig *before* the user hits the connect button, I can't see any other way of resolving this but to either show a clear visual feedback of the failure or simply refuse a connect before the user have cleared the frequency field. The latter is how it used to work pre v0.10.0. But with the recent rmslist feature I felt we needed to take the less intrusive approach since it would be cumbersome if users without rigcontrol had to clear the freq field after each new node selection.

So as of v0.10.0 users will have to pay attention to the red/green border of the frequency field in order to confirm that the QSY was successful. You could also look for any error in the log and/or have a glance at your radio before hitting that connect button.

A positive sideaffect of the change is that operators are now more likely to check that the frequency is clear before dialing the connection, since the QSY is done immediately after the frequency is entered.

This particular change is one I have dreaded for a long time because of this exact problem. I am open for other solutions to the problem, but keep in mind that some users configure rigcontrol and only occationally start rigctld.. so it is impossible to know the expected behaviour based on the config.

My hope is that operators will learn to watch for the UI indications of a successful/failed QSY over time.

PS: If you issue a connect command with freq parameter in the terminal, Pat will still refuse to connect. So this change does not affect scripts.

**Comment by DC7IA** [comment] 2020-09-24 23:48
I did not even notice the frequency becoming red.

I'd prefer a dialog:

```
Changing the frequency failed.

[abort] [continue]
```

What do you think about a dialog like this?

Would certainly save me from transmitting on the wrong frequency sometimes. :)

**Comment by martinhpedersen** [comment] 2020-09-25 00:00
I think a dialog like that would be very annoying for users that knowingly are not using the rigcontrol features. That is the main issue. If we decide to go down that route, then we would need a "stop nagging me" checkbox at least.

But I really believe most users will learn to pay attention to the red/green frequency border, or check their rig before starting to transmit. You probably should be doing some final checks before hitting the connect button anyway, to make sure the channel is clear.

How about making it even clearer by adding a warning sign next to the frequency or Connect-button, possibly with a tooltip explaining what went wrong?

**Comment by DC7IA** [comment] 2020-09-25 00:13
>I think a dialog like that would be very annoying for users that knowingly are not using the rigcontrol features.

Would not such users simply turn off rigcontrol?
 
> How about making it even clearer by adding a warning sign next to the frequency or Connect-button, possibly with a tooltip explaining what went wrong?

Yeah, like a small red label next to it saying "Check frequency!" or something like that.


Also,

>most users will learn

is a sign that a software isn't intuitive. So far, pat is really intuitive, but UI features a user first needs to learn is not intuitive.
I even completely missed the red numbers, so others will probably, too.

Here's a quick and dirty mockup of what I had in mind:

![Screenshot_2020-09-25_02-09-30](https://user-images.githubusercontent.com/26351852/94212489-9be1a680-fed4-11ea-8a1d-6848e6e70a27.png)

**Comment by martinhpedersen** [comment] 2020-09-25 17:14
> Would not such users simply turn off rigcontrol?

I've seen several pre-configured images and provisioning scripts for the Raspberry Pi that override the default (no rigcontrol) config and provides a start/stop rigctld mechanism as the main method of enabling/disabling the feature. This is my main concern regarding a distruptive popup window.

[Build-a-Pi's `my-rig` default](https://github.com/km4ack/pi-build/blob/9061ac19d13f2692c314d2d42bd41e7156778a33/functions/additional.function#L45) comes to mind as one example.

There is much to consider when changing existing features 😅 

> is a sign that a software isn't intuitive. So far, pat is really intuitive, but UI features a user first needs to learn is not intuitive.
I even completely missed the red numbers, so others will probably, too.

I was thinking more about existing users that may have gotten used to how the old QSY feature was implemented. I don't think new users would have a problem understanding this new approach, but I guess that is debatable.

---------

Anyway, I think we are on to something with a short message and tooltip to better communicate the error situation. I will also disable the Connect button while the user is editing the frequency field so they won't be tempted to hit the "connect" button before the QSY error appears.

Let's try it and revisit this discussion if we're not happy with it 😄 

Appreciate your participation on this topic. It's always helpful having someone to bounce ideas off of 👍

**Closed by martinhpedersen** 2020-09-25 17:14 UTC
Labels: invalid
