### ISSUE TITLE
Some "insertion tags" are missing (like GPS)

### ISSUE THREAD

**Issue by n2ygk** [la5nta/pat#328] opened 2022-03-13 19:19 UTC
I noticed that my gpsd-connected GPS position was not being automatically populated in the GENERAL Forms/Winlink Check In form. It appears that not all the [insertion tags](https://www.winlink.org/sites/default/files/RMSE_FORMS/insertion_tags.zip) are implemented in forms.go:

https://github.com/la5nta/pat/blob/ccb493474debb2a84ee2ab60b292327426c86f8a/internal/forms/forms.go#L737-L755

Here's an example from the browser console showing no replacement of the value of  `{GPS_SIGNED_DECIMAL}` vs. `{MsgSender}` that is replaced by the code above:
```
> ExtGPS
<input name=​"ExtGPS" type=​"hidden" id=​"ExtGPS" value=​"{GPS_SIGNED_DECIMAL}​">​
> MsgSender
<input title=​"Call sign or tactical being used to send mail" readonly=​"readonly" maxlength=​"16" size=​"17" id=​"MsgSender" name=​"MsgSender" value=​"N2YGK">​
```

These correspond to the following lines in the input HTML form:
```
winlink$ grep  -n {GPS_SIG ~/Library/Application\ Support/pat/Standard_Forms/GENERAL\ Forms/Winlink_Check_In_Initial.html
506: if (ans  != '{GPS_SIGNED_DECIMAL}') {document.getElementById('GPS2').value = ans};
1494:<input name="ExtGPS" type="hidden" id="ExtGPS" value="{GPS_SIGNED_DECIMAL}" />
1501:<input name="GPS" type="hidden" id="GPS" value="{GPS_SIGNED_DECIMAL}" />
1513:<input name="GPS" type="hidden" id="GPS" value="{GPS_SIGNED_DECIMAL}" />
winlink$ 

$ grep -n {MsgSender} ~/Library/Application\ Support/pat/Standard_Forms/GENERAL\ Forms/Winlink_Check_In_Initial.html 
1477:    <input title="Call sign or tactical being used to send mail" readonly="readonly" maxlength="16" size="17" id="MsgSender"  name="MsgSender" value="{MsgSender}" />
1573:<input name="testCall" type="hidden" id="testCall" value="{MsgSender}" size="14" maxlength="</table>13" />
```

**Comment by martinhpedersen** [comment] 2022-06-02 20:55
Closing this one as duplicate of #338.

**Closed by martinhpedersen** 2022-06-02 20:55 UTC
