### ISSUE TITLE
"panic: close of closed channel" on exit

### ISSUE THREAD

**Issue by UgoPoddine** [la5nta/pat#158] opened 2019-07-23 12:19 UTC
Hello Martin,

it's not so critical, but I would like to share with you the not clean exit of in any case successful pat Winlink connection :

2019/07/16 21:47:35 ARDOP TNC (ARDOP TNC_1.0.4.1i-BPQ) initialized
2019/07/16 21:47:35 Connecting to HB9AK (ardop)...
2019/07/16 21:47:44 Connected to HB9AK (ardop)
*** WINLINK BERN *** (by SWISS-ARTG)
*** IU1IPB Connected to CMS
[WL2K-5.0-B2FWIHJM$]
;PQ: 16162302
CMS via HB9AK >
>FF
FQ
2019/07/16 21:48:32 Disconnected.
panic: close of closed channel

goroutine 1 [running]:
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ardop.(*broadcaster).Close(...)
        /home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ardop/ctrl_broadcast.go:148
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ardop.(*TNC).close(0x11c9c500)
        /home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ardop/tnc.go:357 +0x6c
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ardop.(*TNC).Close(0x11c9c500, 0x4a4878, 0x11c4dbfc)
        /home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ardop/tnc.go:343 +0x74
main.cleanup()
        /home/martinhpedersen/go/src/github.com/la5nta/pat/main.go:406 +0x5c
main.main()
        /home/martinhpedersen/go/src/github.com/la5nta/pat/main.go:308 +0x5ac

This happens each time that the connection is performed successfully.
Please consider :

a) that pat runs on Raspberry PI 
b) that pat has been installed from the .deb file (pat_0.6.1_linux_armhf.deb)
b) that I'm of course using ARDOP as modem
c) the the connection is not made by the web interface but by small script (attached), used to start and stop ARDOP before calling pat, in any case using the statement pat connect ardop:///$QRZ 
d) that I have no CAT compliant device, then the frequency is set manually, the hamlibs are not used at all and the PPT is managed by ARDOP.

Just for your knowledge
Thank-you for your so useful tool

73, IU1IPB Ugo

**Comment by martinhpedersen** [comment] 2019-07-23 12:32
Thanks for the detailed bug report Ugo!

This is a duplicate of issue #137, and a fix will be included in the (long overdue) next release which will be either v0.6.2 or v0.7.0 depending on the changelog.

73 de LA5NTA/Martin

**Closed by martinhpedersen** 2019-07-23 12:32 UTC
Labels: bug, duplicate
