### ISSUE TITLE
Safari 11: Web GUI Compose screen POST button will not post message

### ISSUE THREAD

**Issue by AI3M** [la5nta/pat#144] opened 2018-08-31 18:21 UTC
Safari 11.1.2, OS X High Sierra.  PAT 0.61.  I start PAT and the Web UI indicates "Green".  I then compose a message by Action | Compose.  When I'm done, I press the POST button but nothing happens.  I can post a message via the command line and have it show up in the Web UI, but I cannot seem to post a message from the Web UI.   The POST button does nothing.  ThThere are no Extensions installed in Safari.  Javascript is enabled.  The Add Attachment dialog will pop fine.

I've checked the .wl2k folder structure and the file and permissions appear consistent throughout the folder structure.  

Thanks for any help.

Jim

**Comment by posixPilot** [comment] 2018-09-18 17:39
I have noticed this issue as well on Pat 0.60 using OSX 11.13.6 and Safari 11.1.2.  The issue does not occur when using Firefox or Safari 12.0 .

  Cheers
  Mike

**Comment by martinhpedersen** [comment] 2019-10-04 19:08
I am unable to reproduce this with Safari 12.1.2.

Any particular reasons for not upgrading to Safari 12? I will of course investigate this further if for some reason users may be stuck with Safari 11. But I will need some help, or find a method for downgrading Safari on my system.

**Comment by posixPilot** [comment] 2019-10-04 20:04
I upgraded to Safari 12 when I encountered the issue last year; I just
posted to make you aware that it seemed to be resolved in Safari 12.

  Thanks!
  Mike

**Comment by martinhpedersen** [comment] 2019-10-04 20:16
Ah, ok I see :) Thank you for the patience, and for reporting status on Firefox and Safari 12.

I'm closing this issue now, since Safari 12 was released over a year ago now and the bug does not seem apparent in later versions.

If anyone is stuck on Safari 11 for some reason, I can re-open the issue. Please let me know :)

**Closed by martinhpedersen** 2019-10-04 20:16 UTC
Labels: bug
