### ISSUE TITLE
Is support for VARA in the project timeline?

### ISSUE THREAD

**Issue by simonsolnes** [la5nta/pat#228] opened 2020-10-24 20:33 UTC

**Comment by martinhpedersen** [comment] 2020-10-24 20:56
Hi Simon,

See these two related pages:
https://github.com/la5nta/wl2k-go/issues/59
https://groups.google.com/g/pat-users/c/YDnCsSjd9cU

I guess a good discussion is due given the frequent requests regarding this topic.

1. Given that VARA is a closed-source proprietary modem limited to x86 on Windows/wine, would VARA support benefit the project? Who would use it?
2. Are we able to obtain sufficient documentation for the host interface protocol?
3. Are the VARA author interested in working with us to faciilitate with debugging and maintaining compatibility in the long run?
4. ARDOP is the competing open-source alternative. What would be the impact on that project if we add support for VARA?
....

Please discuss :-)

**Comment by DC7IA** [comment] 2020-10-24 21:20
Well, "limited to x86 on Windows/wine" is a good point Martin makes. Why not use the brilliant native software that is out there? :)

**Comment by dranch** [comment] 2020-10-24 21:56
The issue is that ARDOP development seems to be stalled out.  ARDOPv1 was initially superseded by ARDOPv2 but was later deemed flawed and deprecated.  John Wiseman G8BPQ did create a variant of ARDOPv1 called ARDOPOFDM but I don't know if it's going anywhere since it seems ARDOPv1 is in a sustaining mode per these posts from Rick Muething (creator of ARDOP):

   https://ardop.groups.io/g/users/topic/28508094#4142
   https://ardop.groups.io/g/users/topic/75274773#4713 
   etc

There might be a new HF modem contender in the works from the FreeDV modem team but I haven't heard much on that front in some time:
   https://ardop.groups.io/g/developers/topic/freedv_ofdm_modem/21211944?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,21211944

Anyway, back to VARA,, it seems to be doing very well but as highlighted in this thread, it's closed source, MS Windows X86 only today, etc:  

   https://winlink.org/sites/default/files/downloads/a_winlink_digital_mode_performance_comparison_based_on_the_ionos_hf_vhf_channel_simulator_-_may_18_2020.pdf

--David
KI6ZHD

**Comment by b34systems** [comment] 2021-07-10 05:59
Greetings all,

This topic is a bit old, but I have been in contact with the VARA author and have the command set for controlling the VARA modem.  If someone can point me to the existing source that shows how the current modems have been implemented, I would be willing to work on it.

As to the point regarding VARA being Windows only, more folks are beginning to pack small windows computers into the field...myself included.  I can understand not making VARA implementation a priority, but I don't think it should be discounted out of hand.  I am willing to work on it if someone more experienced with the Pat source would be willing to simply guide/mentor me in the process.

Jeremy
N8JJA

**Comment by sedlund** [comment] 2021-07-10 06:08
I don't believe the source is available.  VARA exists in a black area of HAM radio.  Some people could convincingly say it is a not open protocol and thus not technically legal to be transmitted on amateur frequencies.

Would be interested if this is not the case.

**Comment by martinhpedersen** [comment] 2021-07-10 07:23
@b34systems - Hi Jeremy!

Please read https://github.com/la5nta/pat/wiki/Adding-transports 😊

Also, have a look on the pactor driver. It is implemented in a separate repo, which IMO is a great way for us to keep things isolated and allow for individual development.

Please keep us posted on your progress, and let me know if you have any questions 👍

**Comment by b34systems** [comment] 2021-07-10 16:18
@sedlund - Scott - an interesting opinion I would be interested in hearing more about via a different forum.  

@martinhpedersen - Martin - I'm sure this will take some time, but looking forward to getting my hands dirty here.  Off to begin the process of documenting how VARA handles commands!

**Comment by sedlund** [comment] 2021-07-11 03:33
thanks @b34systems - thankfully the burden of proof of using  proprietary undocumented codecs on amateur radio does not lay with me.

Would be super excited to see full documentation++

**Comment by b34systems** [comment] 2021-07-11 14:18
@sedlund - I make no promises, but will do what I can! :-)

**Comment by b34systems** [comment] 2021-07-21 19:21
Just an update for anyone who's listening:

Using the command set in the VARA documentation, I have been able to successfully start, communicate with, and close the VARA modems via command line.  I am having some radio trouble, so have not evaluated exactly what is sent, in what order, to which port.  Hopefully, I'll have those issues figured out in the next couple of days.  Once I get a bit further along, I will set up a separate GitHub repository and post the link here.

Jeremy
N8JJA

**Comment by ohanssen** [comment] 2021-08-05 18:25
A box based on Raspberry PI or similar hardware, is ideal for running a small portable server. It should be ideal for Winlink taking the burden of interfacing with various hardware, installing highly specialised software, etc. away from everyones laptop computers. It is unfortunate if running a Winlink station would depend on closed Windows X86 only code.
73
Øyvind, LA7ECA

**Comment by dranch** [comment] 2021-08-28 18:57
Hello Jeremy N8JJA @b34systems,

Any updates on your prototype code working with VARA via WINE and creating a Git fork for people to try it?

I think with people playing with it, we can all help you refine your code and someday get it merged upstream.  For those of you who want ultimately try running this entire stack on ARM processors, you can consider this other project working to get VARA to run via that X86 Windows via WINE via a BOX86 CPU emulator.  All this is far than optimal but considering the sunsetting of ARDOP, this is currently our next best approach for the time being.

--David
KI6ZHD

**Comment by xylo04** [comment] 2021-08-28 19:13
@dranch do you have more information about ARDOP sunsetting? This is news to me.

**Comment by dranch** [comment] 2021-08-28 20:53
Please read my previous posts above in this Github issue for previous details.  There is also a brand new email thread about this with authoritative replies from both Rick Muething, KN6KB (creator of ARDOP) and John Wiseman G8BPQ (author of the Linux port, the OFDM version, etc:  Read from the bottom up:  

   https://ardop.groups.io/g/users/topic/85195337

Ps.  I've been investigating running VARA on 64bit Ubuntu Linux via WINE.  Since these VARA modem programs are 32bit only, WINE wants to drag in 162 packages requiring 178MB more OS space just to start.  Polluting my pure 64bit OS with 32bit compatibility libraries and other stuff is something I'm not all that inclined to do as I've had issues with this in the past.

--David
KI6ZHD

**Comment by xylo04** [comment] 2021-08-28 21:56
Got it, thanks. I understand that ARDOP is basically abandoned at this point, but when I hear "sunset" I usually assume there's an official date when support will be dropped from the ecosystem, and I don't think that's been decided yet. That said, the day will likely come.

**Comment by n8jja** [comment] 2021-08-29 02:33
@dranch - David,

I haven't made a ton of progress over the last month for a couple of reasons.  For one, my radio was having difficulties making connections to the Winlink network with my radios and I had a major project going that just wrapped up on Friday (8/27).  Now I have a bit more time to dedicate to this over the next few weeks.  I did set up a repository on my GitHub for this: 

https://www.github.com/n8jja/Pat-Vara

If you, or anyone else, has any info that you have collected about VARA, please feel free to upload it to that repository or email it to me if you are  not comfortable with that.  In a nutshell, I need to figure out the command sequence and message payload before getting down to the nitty-gritty of coding.  

Thanks for keeping my feet to the fire on this, as I definitely want to get something put together.  

I have not looked at Winelink in depth, but am aware of its existence...the WinRPR looks interesting as well.  I'll have to check that out in more depth as well.  Please feel free to contact me if you have any questions or just want to take this off into another forum!

Jeremy
jeremy (at) mycall.com
N8JJA

**Comment by DC7IA** [comment] 2021-10-19 10:15
> consider this other project working to get VARA to run via that X86 Windows via WINE via a BOX86 CPU emulator ( https://github.com/WheezyE/Winelink/ ). All this is far than optimal

Ooof.

Total lack of performance and complicating the setup.

I prefer native software. xD

I will try VARA when it gets a FOSS client for Linux and/or BSD... :D

**Comment by DC7IA** [comment] 2021-10-19 10:20
> Got it, thanks. I understand that ARDOP is basically abandoned at this point

No, G8BPQ still works on it, but as long as there aren't bugs and it does everything that's needed, there's no need for changes.

"As there is very little development going on with ardop at the moment(...)"

That's from an email from May.

I just sent him another one to ask if he could upload his ARDOP repo somewhere, surely that'd be useful.

**Comment by Spirarementum** [comment] 2022-01-17 02:08
Vouching for VARA.

I am one of the few sailors who said 'goodbye' to Windows aboard my yacht. The problem I am facing is the lack of Winlink clients as it is widely adopted as the main email communication system aboard for getting weather forecasts and position reporting. Winlink Express running under Wine is not great... it works but the Winlink Development Team does not in any way support it so living with annoying shortcomings is the norm. Anyways, back to Vara. It has now been adopted by most RMS stations worldwide and after testing in real-life situations for more than a year now while sailing in remote areas, I can say that it is as good as the Pactor III and maybe better in poor propagation situations. 

I hope this help motivate all the involved peoples in this discussion.

**Comment by haklein** [comment] 2022-03-18 12:06
What about other OFDM alternatives like codec2 (https://github.com/drowe67/codec2)? That would likely be a much better choice than proprietary windows-only VARA.

**Comment by xylo04** [comment] 2022-03-18 13:55
@haklein I would love to stay away from VARA due to its licensing and technical problems. But practically, are there any RMS stations that accept codec2 as a transport? It's definitely not the norm right now. [ARSFI's published RMS list](https://winlink.org/RMSChannels) is pretty clear about which transports are officially supported: Packet (+Robust), PACTOR, ARDOP, and VARA (+FM).

I'm happy to build in codec2 if we would like to experiment with it as a community, but priority-wise, VARA must come first because it's what people are actually using.

**Comment by olewsaa** [comment] 2022-04-10 20:57
> Vouching for VARA.
> 
> I am one of the few sailors who said 'goodbye' to Windows aboard my yacht. The problem I am facing is the lack of Winlink clients as it is widely adopted as the main email communication system aboard for getting weather forecasts and position reporting. Winlink Express running under Wine is not great... it works but the Winlink Development Team does not in any way support it so living with annoying shortcomings is the norm. Anyways, back to Vara. It has now been adopted by most RMS stations worldwide and after testing in real-life situations for more than a year now while sailing in remote areas, I can say that it is as good as the Pactor III and maybe better in poor propagation situations.
> 
> I hope this help motivate all the involved peoples in this discussion.

The Raspberry is now widely used both onboard and in the field. Viewing using a mobile and a tablet, but all server services running on RPi. I would like to see adaptation og of more and more software for the RPi. Nothing would suite small radios like my G90 better than a RPi. Native open source (like GNU lic.) VARA would be a major step forward. I hope that any new development will include RPis. For x86 there are a very limited options for small systems like the RPi. Not to mention the power usage of x86 systems.

**Closed** 2022-11-10 05:42 UTC
Labels: question

**Comment by martinhpedersen** [comment] 2022-11-10 05:44
Closed this as VARA is now supported (albeit not --listen yet).
