### ISSUE TITLE
ax.25 AGWPE + Direwolf: keeps trying to connect after I cancel attempt?

### ISSUE THREAD

**Issue by amatecha** [la5nta/pat#405] opened 2023-05-04 06:40 UTC
I'm not sure if this is a valid bug or not, but I don't know how to troubleshoot further to narrow down the issue more specifically.  Would love to get some tips on what I can do to more precisely narrow down the issue.

* Linux Mint 21.1
* kernel 5.15.0-71-generic x86_64
* pat 0.14.1 (62ac29e)
* direwolf 1.7F (Apr 26 2023)
* Digirig for soundcard/PTT
* hamlib for CAT control (QSY)

I was having trouble connecting to a couple local packet Winlink gateways today (station wasn't coming in clearly enough to be decoded), so I wanted to cancel the attempt, because it was hopeless.  Pat's web UI indicated it was canceled (top left button even said "Ready"), but Direwolf just kept trying to connect.  I was using the new AGWPE TCP connectivity, which I suspect to be an important clue to the problem, as I don't recall having this problem last week when I was trying pat 0.13.x, same Direwolf version, and Linux ax.25 ports.  Direwolf doesn't TX on its own (that I know of), so I am not suspecting it much here, unless it ignored a command or something.  It struck me as Pat continuing its connection flow regardless of the UI showing that it had canceled.

PTT works fine, it starts/stops TX just fine if I just connect to a RMS gateway as per usual.  No problems whatsoever sending/receiving a bunch of packet Winlink emails today.   Just this weird quirk with the inability to cancel a connection attempt.  I ended up just Ctrl-C'ing Direwolf to stop the unintended connection attempts.

Anyway, if there's something I can do to better narrow down the issue, please let me know.   Thanks for any tips you can suggest.  (I also spotted a small typo along the way, for which I've [created a quick PR](https://github.com/la5nta/pat/pull/406) to correct the typo) ;)

**Comment by martinhpedersen** [comment] 2023-05-04 16:38
Thanks for reporting this 🙂 

It would be very helpful if you could reproduce and provide a complete log output with debug logging turned on.

Just run `AGWPE_DEBUG=1 pat http` and you should see lots of debug messages related to the AGWPE protocol in your terminal. Reproduce the issue with this turned on, and paste the complete log into a comment here. Thank you 😄

**Comment by martinhpedersen** [comment] 2023-05-06 16:44
Thanks!

I have not concluded yet, but some observations:
* After we have sent the disconnect command ('d' frame), direwolf does not acknowledge by sending a 'd' frame back. Instead it keep sending SABM frames over the air until it hits the connect timeout, at which the 'd' frame is sent:
   ```
   2023/05/05 08:48:09 -> Port: 0. Kind: C. From: VA7EKA. To: VE7HNY-10, Data: ""
   2023/05/05 08:48:24 -> Port: 0. Kind: d. From: VA7EKA. To: VE7HNY-10, Data: ""
   2023/05/05 08:48:58 <- Port: 0. Kind: d. From: VE7HNY-10. To: VA7EKA, Data: "*** DISCONNECTED RETRYOUT With VE7HNY-10\r\x00"
   ```
* qtsoundmodem behaves differently. It immediately acknowledges the 'd' frame sent by Pat and sends one final packet over the air (I'm guessing the DISC frame):
   ```
   2023/05/06 18:25:43 -> Port: 0. Kind: C. From: NODE-1. To: NODE-2, Data: ""
   2023/05/06 18:25:47 -> Port: 0. Kind: d. From: NODE-1. To: NODE-2, Data: ""
   2023/05/06 18:25:47 <- Port: 0. Kind: d. From: NODE-2. To: NODE-1, Data: "*** DISCONNECTED From Station NODE-2\r\x00"
   ```


So far it looks like Pat behaves as expected. My current theory is that Direwolf ignores the 'x' (disconnect) command sent from Pat, but I have to debug some more to confirm this.

**Comment by martinhpedersen** [comment] 2023-05-06 17:06
It could be argued that Pat should block on the disconnect call until aknowledged by the modem. Then at least the UI would indicate that it's still dialing until the modem gives up.

That might be an improvement to consider on our end.

**Comment by wb2osz** [comment] 2023-05-07 01:43
The dev branch of direwolf has been modified so that an AGW 'd' command will abort a connection attempt in progress.
See also  https://github.com/wb2osz/direwolf/issues/275 .

73,
John WB2OSZ

**Comment by amatecha** [comment] 2023-05-07 06:14
Oh wow, thanks John!  You just happened to see this I guess??  Would this be a complete fix for the issue, where Pat doesn't need to do anything different to mitigate the issue?

**Comment by martinhpedersen** [comment] 2023-05-07 12:52
Thanks for listening in and for the fix @wb2osz 😀

**Comment by dranch** [comment] 2023-05-07 15:03
I pointed John to the issue as it looked like a Direwolf issue.  Great to see he was able to fix the issue so fast!

**Comment by amatecha** [comment] 2023-05-08 02:20
Ah perfect.  Thanks @dranch!   Nice, good addition as well @martinhpedersen   :)  This is like the most thorough handling of any bug I've ever filed an issue about, I think!  hahah ;)

**Comment by amatecha** [comment] 2023-05-17 21:43
I think this bug can be closed now?  It seems I have the ability to, but I wasn't sure if I should close it or if an official contributor/maintainer should :sweat_smile:

**Comment by wb2osz** [comment] 2023-05-18 00:03
Thanks for pointing out the problem.
The submitter also has the ability to close an issue.
Closing now.

**Comment by martinhpedersen** [comment] 2023-05-18 09:26
I usually keep issues open until the fix/feature has been released. But in this case, since the bug was in Direwolf, I think we can close it early.

Thanks!

**Closed by martinhpedersen** 2023-05-18 09:26 UTC
Labels: bug
