### ISSUE TITLE
Inconsistency in API

### ISSUE THREAD

**Issue by frspin** [la5nta/pat#451] opened 2024-06-14 13:32 UTC
API for connecting is

localhost:8080/api/connect/?url=[mode]:///[call]?freq=[freq]&bw=[bandwidth]

and this is what is used in Web Gui and what is working.

But rmslist return an incorrect url:

localhost:8080/api/rmslist?mode=[mode]

return as url: 

[mode]:///[call]?bw=[bandwidth]&freq=[freq]

with bw and freq exchanged and this in incorrect and not working.

Regards
Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment] 2024-06-14 20:42
Hi,

Sorry, I'm having difficulties understanding the problem. Would you please care to elaborate?



> with bw and freq exchanged and this in incorrect and not working.

Do you mean the ordering of the query parameters within the URL is different?


Thank you!

**Comment by martinhpedersen** [comment] 2024-06-14 20:45
It would be helpful with a concrete example, including error messages and/or a description of what you expect vs what you observe.

Thanks!

**Comment by frspin** [comment] 2024-06-15 07:03
Il 14/06/24 22:46, Martin Hebnes Pedersen ha scritto:
> It would be helpful with a concrete example, including error messages 
> and/or a description of what you expect vs what you observe.

With correct order of query parameters rig correctly change frequency 
and transmit.

With incorrect order, as returned by api/rmslist?mode=[ardop|vara], rig 
don't change frequency and transmit on current (wrong) frequency.

So the url returned from api/rmlist?mode=[mode] is incorrect.

Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment] 2024-11-23 21:18
I am unable to reproduce this issue. In fact, the ordering of the query parameters can't possible affect the execution as the code parses the complete URL into a [map](https://go.dev/blog/maps) which (if iterated) provides no guarantee as to the ordering of the keys ([¶](https://go.dev/blog/maps#iteration-order)). IIRC the HTTP standard is clear on this as well.

Here's one example as to how we grab values from the URL: https://github.com/la5nta/pat/blob/823b991b25159ee6544f70bca7f9ecf0f4b802a7/connect.go#L162

Maybe the rig didn't change frequency because of some other issue?

We need some concrete examples (both API calls and observed log output) in order to dig deeper into this. I will close this for now, and re-open when we have some concrete details to pursue.

**Closed by martinhpedersen** 2024-11-23 21:18 UTC
