### ISSUE TITLE
pat 0.14.0 ignores agwpe.addr setting in config.json

### ISSUE THREAD

**Issue by AG7GN** [la5nta/pat#401] opened 2023-04-30 22:38 UTC
Thanks so much for adding this AGWPE feature.

Hardware: Raspberry Pi 4B 
OS: Raspberry Pi OS (Bullseye) 32-bit with latest updates

I have Direwolf set up to listen on port 8011 for AGW. It appears that pat ignores the `agwpe.addr` setting in `config.json`. Any change of the `agwpe.addr` from the default `localhost:8000` in `config.json` is ignored. If I set up `config.json` like this: 

```
  "ax25": {
    "engine": "agwpe",
    "beacon": {
      "every": 3600,
      "message": "Winlink P2P",
      "destination": "IDENT"
    },
    "rig": "rigctld",
    "agwpe": {
      "addr": "localhost:8011",
      "radio_port": 0
    }
  },
```
pat produces this error:

`Listener ax25+agwpe failed: AGWPE TNC initialization failed: dial tcp [::1]:8000: connect: connection refused`

pat shouldn't be trying to connect to `localhost:8000` with the above configuration. When setting Direwolf to use AGW port 8000 and using the default agwpe port in `config.json` it works fine.

**Comment by martinhpedersen** [comment] 2023-05-01 07:48
It looks like you have the `agwpe` object nested inside `ax25`? It should be at the root-level 😊

(Sometimes after an upgrade it might be easier to move the old config file to a backup location, forcing Pat to generate a new default config file. Then you can manually move your changes over from the old file.)

**Comment by martinhpedersen** [comment] 2023-05-01 08:19
Just did a quick test. It does work as intended as you add the `agwpe` object at the correct level. Closing this 🙂

**Closed by martinhpedersen** 2023-05-01 08:19 UTC
Labels: invalid

**Comment by AG7GN** [comment] 2023-05-01 17:26
Sorry! Dumb mistake on my part to not put the `agwpe` entry on the root level.
